version: '3'

services:
  server-bot:
    container_name: Leonidas
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #required
    env_file:
      - ./.env  #  environment:
